---
- hosts: all
  become: yes
  tasks:
    - name: Install package GIT
      package:
        name: git
        state: latest
    - name: Install package golang-myip
      package:
        name: go-toolset
        state: latest
   
    - name: Obtention de l'adresse ip
      command: 

